services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=resume_db
      - POSTGRES_USER=myhadiusername
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432  # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
    volumes:
      - postgres_data_resume:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "resume_db", "-U", "myhadiusername"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://myhadiusername:postgres@db:5432/resume_db
      - DEBUG=True

    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    # command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 config.wsgi:application"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
volumes:
  postgres_data_resume: